#!/usr/bin/perl -w
#
# Name: headings-2-link.pl
#
# Autor: Axel Konrad (akli)
# Copyright Axel Konrad 2022, wtfpl 2.0
# see http://www.wtfpl.net/txt/copying/
#
# Verwendung für das siduktion Handbuch.
# Extrahieren und Aufbereiten der Überschriften aus den .md-Dateien.
# Es werden ausschließlich nummerierte Dateien ausgewertet.
#
# Aufruf:
# Als User in einem Terminal in den Ordner /development wechseln.
# Hier den Programmnamen und, durch Leerzeichen voneinander getrennt, die aus zwei
# Buchstaben bestehenden Kürzel für die Sprachen, in denen das Handbuch erstellt
# werden soll, eingeben. Die Sprachkürzel müssen den Namen der Unterordner in /data
# entsprechen.
# Beispiel: ./headings-2-link.pl de
# Die Überschriften-Link-Liste mit dem Namen "headinglinks-de" befinden sich dann
# im Ordner /development.
#
# -----------
# Use for the siduction manual.
# Extract and prepare the headings from the .md files.
# Only numbered files are evaluated.
#
# Call:
# As user in a terminal change into the folder /development.
# Enter the program name and, separated by spaces, the two-letter abbreviations
# for the languages in which the manual is to be created. The language abbreviations
# must correspond to the names of the subfolders in /data folder.
# Example: ./headings-2-link.pl en
# The heading links list with the name "headinglinks-en" are then located
# in the /development folder.
#
#

use strict;
use File::Basename;
#use Unicode::Normalize;

my ($FILE, $H_CLASS, $H_TEXT, $LINK, $LANGCODE, $HEADER, $DE_HEADER, $EN_HEADER);
my (@QUELLE, @DATEIEN, @HLTEXT, @HLFILE);


# General tests

die "Language shortcode is missing.\nUsage:\nEnter the program name and, separated by spaces, the two-letter shortcode\nfor the languages in which the manual should be created. The language shortcode\nmust correspond to the names of the subfolders in /data.\n" if @ARGV < 1;

foreach (@ARGV) {
    next if (/de|en/);          # add language shortcode if an additional language is available
    die "The given language shortcode \"$_\" is not supported.\n";
}

foreach $LANGCODE (@ARGV) {


# The header text for the files

$DE_HEADER = "#\n# Name: headinglinks-de\n#\n# DIESE DATEI NICHT EDITIEREN\n#\n# Das Skript 'heading-2-link.pl' im Verzeichnis '/development'\n# erzeugt sie automatisch.\n# Die Datei listet alle Überschriften des siduction-Handbuchs mit den\n# daraus generierten Link.\n# Im ersten Teil sortiert nach den nummereirten Dateinamen.\n# Im zweiten Teil alphabetisch sortiert nach den Überschriften (Sprungadressen).\n#\n#\n# VERWENDUNG\n#\n# Um einen Link in deinen Text einzufügen, kopiere den Teil nach 'Link:' und\n# füge den Text, der angezeigt werden soll, zwischen den eckigen Klammern ein.\n#\n\n";

$EN_HEADER = "#\n# Name: headinglinks-en\n#\n# DO NOT EDIT THIS FILE\n#\n# It is automatically generated by the script 'heading-2-link.pl' from the\n# directory '/development'.\n# The file lists all the headings of the siduction manual with the link\n# generated from them.\n# In the first part sorted by the numbered filenames.\n# In the second part alphabetically sorted by the headings (jump addresses).\n#\n#\n# HOW TO USE\n#\n# To insert a link in your text, copy the part after 'Link:' and put the text\n# to be displayed between the square brackets.\n#\n\n";

    if ($LANGCODE eq "de") {
        $HEADER = $DE_HEADER;
    } else {
        $HEADER = $EN_HEADER;
    }


# Read in files and process them one by one.

    @DATEIEN =  <../data/$LANGCODE/0*>;

    foreach $FILE (@DATEIEN) {
        chomp($FILE);
    
        open(DATEI, "$FILE") || die "$FILE nicht gefunden\n";
        @QUELLE=<DATEI>;
        close(DATEI);
        
        $FILE =~ s!../data/$LANGCODE/!!;

# Start searching headings.

        while (@QUELLE) {
            $_ = shift @QUELLE;
            chomp($_);
    
            if (/^~{3,}/) {
                    # Remove code blocks completely.
                $_ = shift @QUELLE;
                until (/^~{3,}/) {
                    $_ = shift @QUELLE;
                }
                $_ = shift @QUELLE;
            }
                    # Skip all, except headings.
            next unless /^#{1,4}/;
        
                    # Disassemble and reassemble lines.
            $H_CLASS = $_;
            $H_CLASS =~ s/^(#{1,4}) .*/$1/;

            $H_TEXT = $_;
            $H_TEXT =~ s/^#{1,4} (.*)/$1/; 
        
            $LINK = "\[\]\($FILE\#$H_TEXT\)";
            $LINK =~ s!(.*)!\L$1!;
            $LINK =~ s!( )!-!g;
            $_ = "$FILE   $H_CLASS $H_TEXT   Link:$LINK\n";
            push @HLFILE,$_;
        
            $_ = sprintf "%s~%4s~%s   Link:%s\n", $H_TEXT, $H_CLASS, $FILE, $LINK;
            push @HLTEXT,$_;
            @HLTEXT = sort { "\L$a" cmp "\L$b" } @HLTEXT;
        }
    }

# Write into outputfile.

    open (DATEI, ">", "./headinglinks-$LANGCODE") || die "Kann nicht schreiben.\n";
    print DATEI $HEADER;
    print DATEI @HLFILE;
    #    print @HLFILE;
    print DATEI "\n\n\n";
    foreach (@HLTEXT) {
        s!\A(.*?)~(.*?)~(.*?)\Z!$2 $1   $3!;
        print DATEI "$_";
    #    print "$_";
    }
    close(DATEI);
    @HLFILE = ();
    @HLTEXT = ();

}
