#!/bin/sh

# Name "md2html5"
#
# Autor: Axel Konrad (akli)
# Copyright Axel Konrad 2021, wtfpl 2.0
# see http://www.wtfpl.net/txt/copying/
#
# Verwendung für das siduktion Handbuch.
# Erzeugung einzelner .html-Dokumente aus den .md-Dateien
# des Ordners "sidu-manual/data/de/"
#
# Die Pfade müssen an die individuellen Gegebenheiten angepasst werden.
#

if [ ! -d <Pfad_zu>/data/de/html/ ]
then
   mkdir <Pfad_zu>/data/de/html/
fi

for i in <Pfad_zu>/data/de/clean/*;
do
    pandoc -s --template=<Pfad_zu>/development/pandoc_template.html5 --toc --toc-depth=4 "$i" -o <Pfad_zu>/data/de/html/$(basename $i .md).html;
done

for i in <Pfad_zu>/data/de/html/*;
do
    sed -i -E 's#(_de\.)md#\1html#g' "$i";
done


