#!/bin/sh
# Wrapper script around pandoc
# Provides templates to apply with pdf processing
# Copyright Claes Holmerson 2010, GPL licensed (see COPYING for details)
# Copyright Hendrik Lehmbruch 2021, GPL licensed (see COPYING for details)
# Copyright Axel Konrad 2021, GPL licensed (see COPYING for details)
# Added code to generate siduction manual.
# Name: md2pdf within siduction manual /development folder.
# Usage:
#   change into siduction .md-file folder and type
#   ../../development/md2pdf
#

# directories, based on the fact we use it in folder contain .md-files.
header=../../development/pandoc-header-pdf.tex
searchpath=./:./images/:../../sys-images/

# page options
paper=a4paper
#hmargin=2cm
#vmargin=3.0cm
#margin=20mm
#fontsize=10pt
#fontsize=11pt
fontsize=12pt
#mainfont=Cambria
#sansfont=Corbel
#monofont=Consolas
mainfont="Liberation Sans"
sansfont="Liberation Sans"
monofont="Liberation Mono"
language=german
#language=swedish
nohyphenation=false
linkcolor=blue

columns=onecolumn
#columns=twocolumn

geometry=portrait
#geometry=landscape

#alignment=flushleft
#alignment=flushright
#alignment=center

# Verarbeiten der Dateien zur Erzeugung des PDF:
#  - Sicherungsordner anlegen und Dateien kopieren.
#  - Im Sicherungsordner die Dateiliste erstellen
#  - pandoc (LaTex) Mettatag aus allen Dateien entfernen.
#  - pandoc (LaTex) Mettatag nur in der ersten Datei einfügen.
#  - Dateinamen auf Link anderer Handbuchseiten entfernen.
#  - Ordner für das PDF erstellen.
#  - pandoc ausführen
#  - Sicherung zurückkopieren und Sicherungsordner löschen.

mkdir ../sicherung/ || exit 1

cp -a ./* ../sicherung/ 2>/dev/null

LISTE=$(ls [[:digit:]]*)

for i in $LISTE ; do sed -i -E '/^% \w/d' "$i"; done 

sed -i -e '1 i% Siduction Handbuch' -e '1 i% siduction Team' -e "1 i% $(date +%F)" 0000-*

for i in $LISTE ; do sed -i -e 's/([-_./[:alnum:]]*de.md#/(#/g' "$i"; done

if [ ! -d ./pdf ]; then mkdir ./pdf; fi

echo PDF in Arbeit.

pandoc -N --toc --toc-depth=4 -p --pdf-engine=xelatex --listings -H $header --resource-path=$searchpath --highlight-style tango -V language=$language -V paper=$paper -V hmargin=$hmargin -V vmargin=$vmargin -V linkcolor=$linkcolor -V geometry:margin="$margin" -V mainfont="$mainfont" -V sansfont="$sansfont" -V monofont="$monofont" -V geometry=$geometry -V alignment=$alignment -V columns=$columns -V fontsize=$fontsize -V nohyphenation=$nohyphenation $LISTE -o ./pdf/siduction-manual_de.pdf

cp -a ../sicherung/* ./ && rm -r ../sicherung

