#!/bin/sh
# Wrapper script around pandoc
# Provides templates to apply with pdf processing
# Copyright Claes Holmerson 2010, GPL licensed (see COPYING for details)

# directories 
header=../../development/pandoc-header-pdf_akli.tex
searchpath=./:../../de_md/:../static/images-de/

# page options
paper=a4paper
#hmargin=2cm
#vmargin=3.0cm
#margin=20mm
#fontsize=10pt
#fontsize=11pt
fontsize=12pt
#mainfont=Cambria
#sansfont=Corbel
#monofont=Consolas
mainfont="Liberation Sans"
sansfont="Liberation Sans"
monofont="Liberation Mono"
language=german
#language=swedish
nohyphenation=false

columns=onecolumn
#columns=twocolumn

geometry=portrait
#geometry=landscape

#alignment=flushleft
#alignment=flushright
#alignment=center

linkcolor=blue


date="`date -u`"
# "`date -u '+%Y-%m-%d'`" 

# the command
pandoc -N --toc --toc-depth=4 -p --pdf-engine=xelatex --listings -H $header --resource-path=$searchpath \
-M  date="$date" \
-V language=$language -V paper=$paper -V hmargin=$hmargin -V vmargin=$vmargin \
-V geometry:margin="$margin" -V mainfont="$mainfont" -V sansfont="$sansfont" -V monofont="$monofont" \
-V geometry=$geometry -V alignment=$alignment -V columns=$columns \
-V fontsize=$fontsize -V nohyphenation=$nohyphenation -V linkcolor=$linkcolor \
$@
