#! /bin/bash
set -e

if ! grep -q "sidu-manual" /etc/hosts ; then
	# if the last newline is missing:
	echo "" >>/etc/hosts
	ADDR=86
	while grep -q "127.0.0.$ADDR" /etc/hosts ; do
		ADDR=$(expr $ADDR + 1)
	done
	echo "127.0.0.$ADDR sidu-manual" >>/etc/hosts
	echo "virtual host installed: sidu-manual ($ADDR)"
fi

# Create the links from the toolkit:
pushd /usr/share/sidu-manual >/dev/null
SRC=../sidu-base
function MkLink(){
	if [ ! -L $1 ] ; then
		ln -sf $2/$1 $1
	fi
}
function MkLink2(){
	if [ ! -L $2 ] ; then
		ln -sf $1 $2
	fi
}

# Create the links to the shellserver:
SRC_INI=/usr/share/sidu-base/backend
cd $SRC_INI
SRC=../../sidu-manual/backend
MkLink2 /var/cache/sidu-base/public /usr/share/sidu-manual

popd >/dev/null

#DEBHELPER#

exit 0
 
